### ISSUE TITLE
Missing config-files/ and app-scripts/ directories?

### ISSUE THREAD

**Issue by dijkstracula** [uclasystem/MemLiner#1]
Hi,

I was hoping to inspect the JVM options that you were using to spawn, for instance, your Spark benchmarks, in your paper.  Appendix A indicates that some shell scripts are located in `MemLiner/app-scripts/` and `MemLiner/config-files/`, but those directories aren't check in here, and it isn't immediately obvious if they need to be pulled in from some third-party location as part of the build process.  _(Edit: I should say that the `scripts/` directory in this repository also appears to contain the contents of `rswap/` in Appendix A?)_

It'd be great if those script directories could be added or if I could be pointed to them if they reside elsewhere.  Thanks!

Nathan

**Comment by mahaoran1997** [comment]
Hi Nathan, 

We just updated the missing scripts to the repo. Thanks!

Best,

**Comment by dijkstracula** [comment]
Thanks, Haoran, and congrats on the paper!

Nathan
